schedules:
  - cron: "0 18 * * *"
    always: true
    displayName: "Daily Sync"
    branches:
      include:
        - main

trigger: none

pool:
  name: "bytrcmdopp000"

jobs:
  - deployment: "main"
    displayName: "main"
    environment: "production"
    pool:
      name: "bytrcmdopp000"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              clean: true
              displayName: "checkout repository"
              enabled: true
              fetchDepth: 1
              timeoutInMinutes: 3
            - task: AzureCLI@2
              displayName: "deploy infrastructure"
              enabled: true
              inputs:
                arguments: >-
                  -DeploymentName '$(Build.BuildId)'
                  -ResourceGroupName 'byteterrace'
                  -TemplateFilePath '$(Pipeline.Workspace)/s/main.bicep'
                azureSubscription: "byteterrace-mpn | byteterrace"
                failOnStandardError: true
                inlineScript: |
                  [CmdletBinding()]
                  param(
                      [Parameter(Mandatory = $true, Position = 0)]
                      [string]$DeploymentName,
                      [Parameter(Mandatory = $true, Position = 1)]
                      [string]$ResourceGroupName,
                      [Parameter(Mandatory = $true, Position = 2)]
                      [string]$TemplateFilePath
                  )
                  begin {}
                  process {
                      az deployment group create `
                          --name $DeploymentName `
                          --resource-group $ResourceGroupName `
                          --template-file $TemplateFilePath;
                  }
                  end {
                      return 0;
                  }
                powerShellIgnoreLASTEXITCODE: true
                scriptLocation: "inlineScript"
                scriptType: "pscore"
                visibleAzLogin: false
