name: '$(Date:yyyyMMdd).$(Rev:r)'

trigger:
  batch: true
  branches:
    include:
    - 'main'

resources:
  repositories:
  - repository: 'AzureDevOpsTemplates'
    name: 'Azure/DevOps.Templates'
    ref: 'refs/heads/main'
    type: 'git'

extends:
  template: ${{ format('{0}/Pipelines/Generic.yaml@AzureDevOpsTemplates', variables['Pipeline.Workspace']) }}
  parameters:
    stages:
    - template: './Pipeline-Build-Stages.yaml'
    - template: './Pipeline-Deploy-Stages.yaml'
